#!/bin/sh
#
# Copyright (C) 2020 TDT AG <development@tdt.de>
#
# This is free software, licensed under the GNU General Public License v2.
# See https://www.gnu.org/licenses/gpl-2.0.txt for more information.
#

[ "$ACTION" = "ifup" ] \
	|| [ "$ACTION" = "ifdown" ] \
	|| [ "$ACTION" = "disconnected" ] \
	|| [ "$ACTION" = "connected" ] \
	|| exit 1

[ -n "$INTERFACE" ] || exit 2

. /lib/mwan3/led-mwan3-iface.sh
main "$INTERFACE"
